# Generated by Django 2.1.2 on 2018-11-19 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easycancha', '0002_platform_platformuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimereservation',
            name='platformuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='easycancha.PlatformUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurrentreservation',
            name='platformuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='easycancha.PlatformUser'),
            preserve_default=False,
        ),
    ]
